# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

############################################################
# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate

############################################################
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
url: "https://etri-xainlp.github.io/" # the base hostname & protocol for your site, e.g. https://example.com
baseurl: "" # the subpath of your site, e.g. /blog
image: "/img/intro/01_cover.png"
title: "XAINLP Project"
description: "전문가 의사결정 지원 인공지능 기술 개발"
home_title: "Software Reposotiries"
home_subtitle: "프로젝트를 통해 개발된 소프트웨어"
about_title: "Project Introduction"
about_subtitle: "프로젝트에 대한 개략적 소개"
github_username: ""
medium_username: ""
twitter_username: ""

############################################################
# Phantom settings
paginate: 10
header_text: "XAINLP Project"
header_link: "/"
footer_text: "© 2022 XAINLP Project"
footer_link: "/about"
enable_nav: true
nav_item:
  - { url: "/about", text: "About" }
  - { url: "/#portfolio", text: "Reposotiries" }
